Update kv sdk
Azure-Samples/sql-database-dotnet-manage-sql-server-keys-with-azure-key-vault pull request #2
Opened 2021-12-01 09:46 UTC by v-yilinhu

1. Update KenVault SDK to T2

2. Update files:

    - ./ManageSqlServerKeysWithAzureKeyVaultKey.csproj
    - ./Program.cs

2021-12-01 19:21 UTC, heaths commented on ManageSqlServerKeysWithAzureKeyVaultKey.csproj
> +	 <OutputType>Library</OutputType>
Nit: inconsistent spacing.

2021-12-01 19:21 UTC, heaths commented on Program.cs
> +                var kvClient = new KeyClient(vaultUri: new Uri(vault.VaultUri), credential: new DefaultAzureCredential());
Nit: why use named parameters here when you don't anywhere else in this file it seems?

2021-12-01 19:23 UTC, heaths requested changes

2021-12-01 19:23 UTC, heaths commented on Program.cs
> +                var keyBundle = kvClient.CreateKeyAsync(keyName, KeyType.Rsa).GetAwaiter().GetResult();
1. With network calls it's generally better to use async code all the way up, for example, having an `async static Main`.
2. If making your whole code path async isn't desirable, we do provide synchronous APIs you should use here instead e.g., `kvClient.CreateKey(...)` instead of doing async over sync (common problems can arise).

2021-12-02 18:32 UTC, heaths requested changes

2021-12-02 18:32 UTC, heaths commented on Program.cs
> +        public static async void RunSample(IAzure azure)
Never use `async void` unless you will never want to monitor for when it's done (e.g. await it). `async Task`.

2021-12-02 18:32 UTC, heaths commented on Program.cs
> +        public async static void Main(string[] args)
Should be `async Task`, but you certainly want to `await RunSample` below or it will exit the app before the `RunSample` method has time to finish.

Or just use the sync `CreateKey` method I mentioned. Our Track 2 libraries provide both sync and async methods for C# so the `GetAwaiter().GetResult()` was unnecessary.

2021-12-03 19:03 UTC, heaths approved these changes

2021-12-06 02:54 UTC, v-xuto commented
@jongio Please help merge this PR.

2022-01-03 23:15 UTC, merged